language: objective-c
osx_image: xcode7.3

env:
    - ACTION=test  PLATFORM=iOS     DESTINATION='platform=iOS Simulator,name=iPhone 6S'
script:
    - set -o pipefail && xcodebuild -scheme HandyJSONTests -destination "$DESTINATION" $ACTION | xcpretty
